### ISSUE TITLE
app.ts 文件有问题？

### ISSUE THREAD

**Issue by lisiyizu** [vorshen/landlord#1]
/html/js/src/App.ts

![image](https://user-images.githubusercontent.com/12014252/62185616-c057f680-b395-11e9-96e5-b55207d127c8.png)

NetworkConfig 应该改成  DefaultConfig

![image](https://user-images.githubusercontent.com/12014252/62185633-d2399980-b395-11e9-903e-cffc12b99bc3.png)

还有一个问题，执行 ./server.out 报错：
![image](https://user-images.githubusercontent.com/12014252/62185713-175dcb80-b396-11e9-8339-95b1dd4c6c84.png)

**Comment by vorshen** [comment]
1、app.ts问题
已提交fix，抱歉，是我低级错误，改文件名提交后，忘了改app.ts里面了
2、server依赖的config目录下配置文件，编译时是绝对路径，但是是编译机的路径
我尝试改成相对路径
暂时解决办法就是重新编译一下，电脑有clang的话，执行make即可

**Comment by vorshen** [comment]
改成相对路径了，pull下之后看看能否执行～
@lisiyizu

**Comment by lisiyizu** [comment]
文档可以修正一下：
![image](https://user-images.githubusercontent.com/12014252/62189912-c30d1880-b3a2-11e9-9181-a4c0d17f382c.png)


![image](https://user-images.githubusercontent.com/12014252/62189835-978a2e00-b3a2-11e9-9009-85e8ce6dc423.png)

访问还是报错：
![image](https://user-images.githubusercontent.com/12014252/62189979-e1731400-b3a2-11e9-858a-80146d1053cb.png)
点击"快速开始"，好像报了websocket 的问题
![image](https://user-images.githubusercontent.com/12014252/62190003-ecc63f80-b3a2-11e9-8238-59c569c9370c.png)

**Comment by vorshen** [comment]
文档之前修正啦
warning的问题目前不影响使用，后续我fix一下

websocket 200这个，我没遇到这个报错，刚刚搜了一下，是不是你配置了反向代理啊

**Comment by vorshen** [comment]
终于和lisiyizu定位到了问题，是因为前端server的端口和和游戏server冲突了
不同端口号就ok了
