### ISSUE TITLE
可以将第一步详细说明一下吗，每次启动server  26619 segmentation fault  ./server.out

### ISSUE THREAD

**Issue by Neptunesy** [vorshen/landlord#2]

**Comment by vorshen** [comment]
方便截下图么？
「第一步详细说下」，这里指的是ln软链接么？
因为html里面的index.html是web入口文件，这里不能以文件系统访问（否则无法建立socket链接的），必须要从webserver中访问
从webserver中访问方法很多，我列出来的就是用了mac os默认的apache，把html目录软链接到了apache的资源目录，这样就可以从apache访问了。用软链接不直接拷贝，是方便修改代码，直接可以同步

**Comment by Neptunesy** [comment]
那我就明白了 我改用tomcat 好了不熟悉Apache

**Comment by vorshen** [comment]
ok好的～有问题再沟通哈
